# Generated by Django 3.1.4 on 2020-12-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_auto_20201201_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='joinded_on',
        ),
    ]
